AWSTemplateFormatVersion: 2010-09-09
Description: simple ecs creation cloud formation
Metadata: 

Parameters: 

Mappings: 

Conditions: 

Resources: 
  ecsvpc:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 192.168.0.0/24
      EnableDnsSupport: true
      Tags:
        - Key: name
          Value: ecsvpc
  ecsigw:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: name
          Value: ecsigw
  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: 
        Ref: ecsvpc
      InternetGatewayId: !Ref ecsigw

Outputs: