version: '3.7'

services:
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - node_mongo_db:/data/db
    networks:
      custom_1:
        ipv4_address: "172.21.1.2"

volumes:
  node_mongo_db:

networks:
  custom_1:
    driver: bridge
    name: mongo_network
    ipam:
      config:
        - subnet: "172.21.1.0/24"
          gateway: "172.21.1.1"
