version: '3.8'

services:
  nginx:
    build: .
    ports:
      - "8080:80"
    links:
      - php-fpm
    networks:
      - net1
    depends_on:
      - php-fpm

  php-fpm:
    container_name: php-fpm
    build:
      context: ./php
      dockerfile: Dockerfile
    volumes:
      - ./php/src:/var/www/html/
    ports:
      - 9000
    networks:
      - net1
      
networks:
  net1:
    external:
      name: mysql-network