version: '3.7'
services:
  app:
    container_name: docker-node-mongo
    restart: always
    build: .
    ports:
      - '3000:3000'
    
    networks:
      - custom_2

networks:
  custom_2:
    external: 
      name: mongo_network
  