AWSTemplateFormatVersion: 2010-09-09
Description: simple vpc creation templete
Metadata:

Parameters:

Mappings:

Conditions:

Resources:
  jay-vpc:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/20
      EnableDnsSupport: true
      Tags:
        - Key: name
          Value: jay-vpc
  igwName:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: keyname
          Value: value
  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: vpc-id
      InternetGatewayId: !Ref igwName
Otputs:
