version: '3.7'

services:
  node:
    container_name: simple_node
    build: 
      context: ./
      dockerfile: Dockerfile
    volumes:
      - backup:/app
    ports:
      - "3000:3000"

volumes:
  backup: